name: Official Insta Uploader
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
env:
  INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME2 }}
  INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD2 }}
  OTP_SECRET: ${{ secrets.OTP_SECRET }}
  SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
  NEIS_API_KEY: ${{ secrets.NEIS_API_KEY }}
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    # runs-on: ${{ matrix.os }}
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "*.jar"
          tarBall: false
          zipBall: false
          out-file-path: "${{ github.workspace }}/download/"
          token: "${{ secrets.TOKEN }}"
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run jar
        run: |
          ARTIFACT=$(find download -type f -name "**.jar")
          java -jar $ARTIFACT story
